-- Inizializzazione additiva dello schema applicativo QUIZZING.
-- Questo file non contiene DROP, TRUNCATE, DELETE o UPDATE ed e sicuro da
-- rieseguire: crea esclusivamente tabelle e indici mancanti.
-- Le tabelle interne di Django sono gestite da `python manage.py migrate`.

CREATE TABLE IF NOT EXISTS "Utente" (
  "nomeUtente" VARCHAR(100) PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cognome VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Quiz" (
  codice INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creatore VARCHAR(100) NOT NULL REFERENCES "Utente"("nomeUtente") ON DELETE RESTRICT,
  titolo VARCHAR(255) NOT NULL,
  "dataInizio" DATE NOT NULL,
  "dataFine" DATE NOT NULL,
  CHECK ("dataInizio" <= "dataFine")
);

CREATE TABLE IF NOT EXISTS "Domanda" (
  quiz INTEGER NOT NULL REFERENCES "Quiz"(codice) ON DELETE RESTRICT,
  numero INTEGER NOT NULL CHECK (numero > 0),
  testo VARCHAR(1000) NOT NULL,
  PRIMARY KEY (quiz, numero)
);

CREATE TABLE IF NOT EXISTS "Risposta" (
  quiz INTEGER NOT NULL,
  domanda INTEGER NOT NULL,
  numero INTEGER NOT NULL CHECK (numero > 0),
  testo VARCHAR(1000) NOT NULL,
  tipo VARCHAR(10) NOT NULL CHECK (tipo IN ('Corretta', 'Sbagliata')),
  punteggio INTEGER,
  PRIMARY KEY (quiz, domanda, numero),
  FOREIGN KEY (quiz, domanda) REFERENCES "Domanda"(quiz, numero) ON DELETE RESTRICT,
  CHECK (
    (tipo = 'Corretta' AND punteggio IS NOT NULL AND punteggio > 0)
    OR (tipo = 'Sbagliata' AND punteggio IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS "Partecipazione" (
  codice INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  utente VARCHAR(100) NOT NULL REFERENCES "Utente"("nomeUtente") ON DELETE RESTRICT,
  quiz INTEGER NOT NULL REFERENCES "Quiz"(codice) ON DELETE RESTRICT,
  data DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS "RispostaUtenteQuiz" (
  partecipazione INTEGER NOT NULL REFERENCES "Partecipazione"(codice) ON DELETE RESTRICT,
  quiz INTEGER NOT NULL,
  domanda INTEGER NOT NULL,
  risposta INTEGER NOT NULL,
  PRIMARY KEY (partecipazione, quiz, domanda, risposta),
  FOREIGN KEY (quiz, domanda, risposta)
    REFERENCES "Risposta"(quiz, domanda, numero) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS quiz_creatore_idx
  ON "Quiz"(creatore);
CREATE INDEX IF NOT EXISTS quiz_date_idx
  ON "Quiz"("dataInizio", "dataFine");
CREATE INDEX IF NOT EXISTS partecipazione_utente_idx
  ON "Partecipazione"(utente);
CREATE INDEX IF NOT EXISTS partecipazione_quiz_idx
  ON "Partecipazione"(quiz);
CREATE INDEX IF NOT EXISTS partecipazione_data_idx
  ON "Partecipazione"(data);
CREATE INDEX IF NOT EXISTS domanda_quiz_idx
  ON "Domanda"(quiz);
CREATE INDEX IF NOT EXISTS risposta_domanda_idx
  ON "Risposta"(quiz, domanda);
CREATE INDEX IF NOT EXISTS ruq_partecipazione_idx
  ON "RispostaUtenteQuiz"(partecipazione);
